//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _30EJEM_PAGINACION_REPASO_.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPLEADOS_HOSPITAL
    {
        public string APELLIDO { get; set; }
        public string FUNCION { get; set; }
        public string HOSPITAL_COD { get; set; }
    }
}
