//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _30EJEM_PAGINACION_REPASO_.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class EntidadHospital : DbContext
    {
        public EntidadHospital()
            : base("name=EntidadHospital")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<EMPLEADOS_HOSPITAL> EMPLEADOS_HOSPITAL { get; set; }
    
        public virtual ObjectResult<PAGINAR_EMPLEADOS_HOSPITAL_Result> PAGINAR_EMPLEADOS_HOSPITAL(Nullable<int> pOSICION, Nullable<int> hOSPITAL)
        {
            var pOSICIONParameter = pOSICION.HasValue ?
                new ObjectParameter("POSICION", pOSICION) :
                new ObjectParameter("POSICION", typeof(int));
    
            var hOSPITALParameter = hOSPITAL.HasValue ?
                new ObjectParameter("HOSPITAL", hOSPITAL) :
                new ObjectParameter("HOSPITAL", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PAGINAR_EMPLEADOS_HOSPITAL_Result>("PAGINAR_EMPLEADOS_HOSPITAL", pOSICIONParameter, hOSPITALParameter);
        }
    }
}
