<?xml version="1.0" encoding="utf-8"?><Database Name="Hospital" Class="ClsDoctorDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=.;Initial Catalog=Hospital;Integrated Security=True" SettingsObjectName="_03LINQ_TO_SQL_FORM_PRACTICA_01.Properties.Settings" SettingsPropertyName="HospitalConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.DOCTOR" Member="DOCTOR">
    <Type Name="DOCTOR">
      <Column Name="HOSPITAL_COD" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DOCTOR_NO" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="APELLIDO" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ESPECIALIDAD" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SALARIO" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
</Database>