//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _25EEJEM_PLANTILLA_POR_HOSPITAL_AJAX_HIPERVINCULOS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PLANTILLA
    {
        public string HOSPITAL_COD { get; set; }
        public string SALA_COD { get; set; }
        public string EMPLEADO_NO { get; set; }
        public string APELLIDO { get; set; }
        public string FUNCION { get; set; }
        public string T { get; set; }
        public Nullable<int> SALARIO { get; set; }
    }
}
