//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _27EJEM_SESION_CESTA_EMP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMP
    {
        public int EMP_NO { get; set; }
        public string APELLIDO { get; set; }
        public string OFICIO { get; set; }
        public Nullable<int> DIR { get; set; }
        public Nullable<System.DateTime> FECHA_ALT { get; set; }
        public Nullable<int> SALARIO { get; set; }
        public Nullable<int> COMISION { get; set; }
        public Nullable<int> DEPT_NO { get; set; }
    }
}
